"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: std_msgs.msg
  IDL file: Float64MultiArray.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import std_msgs

from robotis_dds_python.idl.std_msgs.msg._MultiArrayLayout_ import MultiArrayLayout_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Float64MultiArray_(idl.IdlStruct, typename="std_msgs.msg.dds_.Float64MultiArray_"):
    layout: MultiArrayLayout_
    data: types.sequence[types.float64]


