"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: std_msgs.msg
  IDL file: MultiArrayDimension.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import std_msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class MultiArrayDimension_(idl.IdlStruct, typename="std_msgs.msg.dds_.MultiArrayDimension_"):
    label: str
    size: types.uint32
    stride: types.uint32


