"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: sensor_msgs.msg
  IDL file: CompressedImage.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import sensor_msgs

# if TYPE_CHECKING:
#     import std_msgs.msg

from robotis_dds_python.idl.std_msgs.msg import Header_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class CompressedImage_(idl.IdlStruct, typename="sensor_msgs.msg.dds_.CompressedImage_"):
    header: Header_
    format: str
    data: types.sequence[types.uint8]


