"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: nav_msgs.msg
  IDL file: Odometry.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import nav_msgs

# if TYPE_CHECKING:
#     import geometry_msgs.msg
#     import std_msgs.msg

from robotis_dds_python.robotis_dds_core.idl.std_msgs.msg import Header_
from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import PoseWithCovariance_
from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import TwistWithCovariance_

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Odometry_(idl.IdlStruct, typename="nav_msgs.msg.dds_.Odometry_"):
    header: Header_
    child_frame_id: str
    pose: PoseWithCovariance_
    twist: TwistWithCovariance_
