"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: builtin_interfaces.msg

"""

from ._Duration_ import Duration_
from ._Time_ import Time_
__all__ = ["Duration_", "Time_", ]
