"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: Point.idl
"""

from dataclasses import dataclass
import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Point_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.Point_"):
    x: float
    y: float
    z: float
