"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: PoseWithCovariance.idl
"""

from dataclasses import dataclass
import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import geometry_msgs

from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Pose_

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PoseWithCovariance_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.PoseWithCovariance_"):
    pose: Pose_
    covariance: types.array[float, 36]
