"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: Pose.idl
"""

from dataclasses import dataclass
import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate

from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Point_
from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Quaternion_

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Pose_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.Pose_"):
    position: Point_
    orientation: Quaternion_
