"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: TransformStamped.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate

# root module import for resolving types
# import geometry_msgs

# if TYPE_CHECKING:
#     import std_msgs.msg

from robotis_dds_python.robotis_dds_core.idl.std_msgs.msg import Header_
from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Transform_

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TransformStamped_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.TransformStamped_"):
    header: Header_
    child_frame_id: str
    transform: Transform_


