"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: Transform.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate

# root module import for resolving types
# import geometry_msgs

from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Vector3_
from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import Quaternion_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Transform_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.Transform_"):
    translation: Vector3_
    rotation: Quaternion_


