"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: nav_msgs.msg
  IDL file: Odometry.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import nav_msgs

if TYPE_CHECKING:
    import geometry_msgs.msg
    import std_msgs.msg



@dataclass
@annotate.final
@annotate.autoid("sequential")
class Odometry(idl.IdlStruct, typename="nav_msgs.msg.Odometry"):
    header: 'std_msgs.msg.Header'
    child_frame_id: str
    pose: 'geometry_msgs.msg.PoseWithCovariance'
    twist: 'geometry_msgs.msg.Twist'


