"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: nav_msgs.msg
  IDL file: Odometry.idl

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate

from robotis_dds_python.idl.geometry_msgs.msg import PoseWithCovariance_, TwistWithCovariance_
from robotis_dds_python.idl.std_msgs.msg import Header_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Odometry_(idl.IdlStruct, typename="nav_msgs.msg.dds_.Odometry_"):
    header: Header_
    child_frame_id: str
    pose: PoseWithCovariance_
    twist: TwistWithCovariance_
