"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: tf2_msgs.msg
  IDL file: TFMessage.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import tf2_msgs

# if TYPE_CHECKING:
#     import geometry_msgs.msg

from robotis_dds_python.robotis_dds_core.idl.geometry_msgs.msg import TransformStamped_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class TFMessage_(idl.IdlStruct, typename="tf2_msgs.msg.dds_.TFMessage_"):
    transforms: types.sequence[TransformStamped_]
    