"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: Point.idl

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Point_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.Point_"):
    x: types.float64
    y: types.float64
    z: types.float64
