"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: Transform.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import geometry_msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Transform(idl.IdlStruct, typename="geometry_msgs.msg.Transform"):
    translation: 'geometry_msgs.msg.Vector3'
    rotation: 'geometry_msgs.msg.Quaternion'


