"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: TransformStamped.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import geometry_msgs

if TYPE_CHECKING:
    import std_msgs.msg



@dataclass
@annotate.final
@annotate.autoid("sequential")
class TransformStamped(idl.IdlStruct, typename="geometry_msgs.msg.TransformStamped"):
    header: 'std_msgs.msg.Header'
    child_frame_id: str
    transform: 'geometry_msgs.msg.Transform'


