"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: geometry_msgs.msg
  IDL file: TwistWithCovariance.idl

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from robotis_dds_python.idl.geometry_msgs.msg import Twist_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class TwistWithCovariance_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.TwistWithCovariance_"):
    twist: Twist_
    covariance: types.array[types.float64, 36]
