"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: sensor_msgs.msg
  IDL file: BatteryState.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import sensor_msgs

#if TYPE_CHECKING:
#    import std_msgs.msg

from robotis_dds_python.robotis_dds_core.idl.std_msgs.msg import Header_


@dataclass
@annotate.final
@annotate.autoid("sequential")
class BatteryState_(idl.IdlStruct, typename="sensor_msgs.msg.dds_.BatteryState_"):
    header: Header_
    voltage: types.float32
    temperature: types.float32
    current: types.float32
    charge: types.float32
    capacity: types.float32
    design_capacity: types.float32
    percentage: types.float32
    power_supply_status: types.uint8
    power_supply_health: types.uint8
    power_supply_technology: types.uint8
    present: bool
    cell_voltage: types.sequence[types.float32]
    cell_temperature: types.sequence[types.float32]
    location: str
    serial_number: str


