"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: sensor_msgs.msg
  IDL file: Image.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import sensor_msgs

# if TYPE_CHECKING:
#     import std_msgs.msg

from robotis_dds_python.robotis_dds_core.idl.std_msgs.msg import Header_

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Image_(idl.IdlStruct, typename="sensor_msgs.msg.dds_.Image_"):
    header: Header_
    height: types.uint32
    width: types.uint32
    encoding: str
    is_bigendian: types.uint8
    step: types.uint32
    data: types.sequence[types.uint8]


