name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y cyclonedds libcyclonedds-dev cmake build-essential
        export CYCLONEDDS_HOME=/usr
        export CMAKE_PREFIX_PATH=$CYCLONEDDS_HOME

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cyclonedds==0.10.2
        pip install -e .
        pip install pytest flake8 black

    - name: Lint and format check
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        black --check robotis_dds_python/ example/

    - name: Run tests
      run: pytest -v --exitfirst --maxfail=1

    - name: Test examples import
      run: pytest tests/test_imports.py
